### Registro de usuario
POST http://localhost:9000/api/register
Content-Type: application/json

{
  "login": "ejemploUsuario",
  "email": "ejemplo@correo.com",
  "password": "123456"
}

### Login de usuario con login
POST http://localhost:9000/api/login
Content-Type: application/json

{
  "loginOrEmail": "ejemploUsuario",
  "password": "123456"
}

### Login de usuario con email
POST http://localhost:9000/api/login
Content-Type: application/json

{
  "loginOrEmail": "ejemplo@correo.com",
  "password": "123456"
}